services:
  animecix-addon:
    build: .
    container_name: animecix-stremio-addon
    restart: unless-stopped
    ports:
      - "7000:7000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

  ngrok:
    image: ngrok/ngrok:latest
    container_name: animecix-ngrok
    restart: unless-stopped
    command:
      - "http"
      - "--url=nineteen-unwritten-similarly.ngrok-free.dev"
      - "animecix-addon:7000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - animecix-addon

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: animecix-cloudflared
    restart: unless-stopped
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "--url"
      - "http://animecix-addon:7000"
    depends_on:
      - animecix-addon

